### PR TITLE
playground: tiproxy needs to override usercfg

### LINKED ISSUE #2339: Start multiple TiProxy by TiUP playground with a config file fails
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```shell
touch cfg
tiup playground v7.5.0 --tiproxy 2 --tiproxy.config cfg --tiflash 0
```

2. What did you expect to see?

The cluster starts successfully

3. What did you see instead?

Only one TiProxy starts and another reports that the port is occupied.
This is because TiUP writes the port to the cfg file and all the TiProxy share the same file.
This is different for TiDB. TiUP won't write the TiDB config file.

4. What version of TiUP are you using (`tiup --version`)?

v1.14.0

### PR DESCRIPTION
**Pull request by xhebox**
### What problem does this PR solve? 

Close #2339 

previously, it doesnt override user config correctly leading to port conflicts when using custom configs for multiple tiproxy instances. TiDB pass ports by cli flags so then are fine.

Also, log-file is not passed

### What is changed and how it works?

1. use different logic than TiDB to generate configs.
2. pass log-file

### Check List 

Tests 

 - Unit test
 - Integration test
 - [x] Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: components/playground/instance/tiproxy.go [hunk 1]
```diff
@@ -68,34 +69,33 @@ func (c *TiProxy) Start(ctx context.Context, version utils.Version) error {
...
-	if err := os.MkdirAll(filepath.Dir(configPath), 0755); err != nil {
-		return err
-	}
-	if err := os.WriteFile(configPath, b, 0644); err != nil {
+	enc := toml.NewEncoder(cf)
+	enc.Indent = ""
+	if err := enc.Encode(spec.MergeConfig(userConfig, map[string]any{
+		"proxy.pd-addrs":            strings.Join(endpoints, ","),
+		"proxy.addr":                utils.JoinHostPort(c.Host, c.Port),
+		"proxy.require-backend-tls": false,
```
Comment (djshow832) [inline components/playground/instance/tiproxy.go:95]: Do we need this line anymore?
