### PR TITLE
fix binpath not work

### LINKED ISSUE #1534: TiUP shouldn't download component binaries when binpath is provided
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
run `tiup playground --mode=tikv-slim --kv.binpath=/xxx/tikv-server` without an installed tikv component.

2. What did you expect to see?
Since I'm using a local binary built from source, TiUP does not need to download the component and would launch with the local binary.

3. What did you see instead?
Instead of launching with the local binary, TiUP starts downloading the tikv component which is not needed
image (2)

4. What version of TiUP are you using (`tiup --version`)?

```
1.5.5 tiup
Go Version: go1.16.7
Git Ref: v1.5.5
GitHash: 01df6de49dbf23af1a3e9d6f71d383c407cdb81
```

### PR DESCRIPTION
**Pull request by nexustar**
### What problem does this PR solve? 

when binpath is provided, tiup still download unesserary component, fix #1534 

### What is changed and how it works?

don't download when binpath is provided,and fix a parameter

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: pkg/exec/run.go [hunk 1]
```diff
@@ -176,36 +176,32 @@ type PrepareCommandParams struct {
...
+		if (p.Component == "playground" || p.Component == "cluster") && semver.Compare(selectVer.String(), "v1.0.0") < 0 {
+			return nil, errors.Errorf("incompatible component version, please use `tiup update %s` to upgrade to the latest version", p.Component)
+		}
+
 		binPath, err = env.BinaryPath(p.Component, selectVer)
 		if err != nil {
 			return nil, err
 		}
 	}
+	installPath, _ := filepath.Split(binPath)
```
Comment (AstroProfundis) [inline pkg/exec/run.go:204]: Better use `filepath.Dir()` for this usage.

**Review by AstroProfundis — APPROVED** [review]
