### PR TITLE
Fix: duplicated pd_servers.name in the topology before truly deploy

### LINKED ISSUE #764: check duplicated  pd_servers.name in the topology before truly deploy the cluster
https://github.com/pingcap/tiup/blob/41f1373cb21df335773ba5b916fc586ff34c0adb/examples/topology.example.yaml#L77
if contains duplicated pd name, we can deploy success, but failed to start pd.

We can add the duplicated name check in https://github.com/pingcap/tiup/blob/41f1373cb21df335773ba5b916fc586ff34c0adb/pkg/cluster/spec/validate.go#L695

So when a user using a topology with duplicated pd name, we will hint the user to update the topology.

### PR DESCRIPTION
**Pull request by anywhy**
### What problem does this PR solve? 
fix #764  pd_servers.name has same name 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cluster/spec/validate.go [hunk 1]
```diff
@@ -794,6 +794,22 @@ func (s *Specification) validateTLSEnabled() error {
 	return nil
 }
 
+func (s *Specification) validatePdPodNames() error {
+	// check pdserver pod name
+	if len(s.PDServers) > 1 {
```
Comment (lucklove) [inline pkg/cluster/spec/validate.go:799]: This check is redundant, prefer to remove the if statement

File: pkg/cluster/spec/validate.go [hunk 2]
```diff
@@ -794,6 +794,22 @@ func (s *Specification) validateTLSEnabled() error {
 	return nil
 }
 
+func (s *Specification) validatePdPodNames() error {
```
Comment (lucklove) [inline pkg/cluster/spec/validate.go:797]: prefer to use the name `validatePDNames` because `Pod` is a term of K8S and we can really deploy TiDB to K8S. So we'd better change it to avoid misunderstanding

File: pkg/cluster/spec/validate.go [hunk 3]
```diff
@@ -794,6 +794,22 @@ func (s *Specification) validateTLSEnabled() error {
...
+	// check pdserver pod name
+	if len(s.PDServers) > 1 {
+		cnt := make(map[string]int)
```
Comment (lucklove) [inline pkg/cluster/spec/validate.go:800]: Prefer to use [StringSet](https://github.com/pingcap/tiup/blob/master/pkg/set/string_set.go):

```
names := set.NewStringSet()

for _, pd := range s.PDServers {
    if pd.Name == "" {
        continue
    }
    if names.Exist(pd.Name) { 
        return errors.Errorf("xxxxxx")
    }
    names.Insert(pd.Name)
}
```

**Review by lucklove — COMMENTED** [review]
Rest LGTM

File: pkg/cluster/spec/validate.go (hunk 3 above)
Comment (anywhy) [reply pkg/cluster/spec/validate.go:800]: got it

**Review by AstroProfundis — APPROVED** [review]
