### PR TITLE
cluster: fix the issue when endpoints are empty in scale-out

### LINKED ISSUE #1226: scale-out action doesn't start tiflash success
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I deployed a cluster which doesn't has any TiFlash node, and then scale-out one TiFlash with the command `tiup cluster scale-out test tiflash.yaml` and execute `tiup cluster display test`.

2. What did you expect to see?
The status of TiFlash node should be `UP`

3. What did you see instead?
The status of TiFlash node is `N/A`. And after I execute `tiup cluster start test -R tiflash`, It's `UP`.

And I tried to debug why this happens, I found the [guide to scale-out tiflash](https://docs.pingcap.com/zh/tidb/stable/scale-tidb-using-tiup#%E6%89%A9%E5%AE%B9-tiflash-%E8%8A%82%E7%82%B9) which says you should `tiup ctl pd -u <pd-host>:<pd-port> config set enable-placement-rules true` before scale-out TiFlash. 

But I found we have do this in the scale-out stage: https://github.com/pingcap/tiup/blob/master/pkg/cluster/spec/tiflash.go#L657

Then I debug the result of `pdClient.UpdateReplicateConfig(bytes.NewBuffer(enablePlacementRules))`, I found that it returns nil error in both `scale-out` and `start` action, but only changes `enable-placement-rules` (`curl pd:port/pd/api/v1/config|grep enable-placement-rules`) to `true` in `start` action. 

In another word, the `pdClient.UpdateReplicateConfig` not work when you `scale-out` tiflash but work when you start `tiflash`. That's not reasonable.

4. What version of TiUP are you using (`tiup --version`)?
v1.3.5 and master

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
Fix #1226 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by 9547** [comment]
/cc @lucklove 

PTAL

File: pkg/cluster/operation/action.go [hunk 1]
```diff
@@ -452,7 +453,13 @@ func EnableMonitored(
 }
 
 // StartComponent start the instances.
-func StartComponent(ctx context.Context, instances []spec.Instance, options Options, tlsCfg *tls.Config) error {
+func StartComponent(
+	ctx context.Context,
+	instances []spec.Instance,
+	options Options,
+	tlsCfg *tls.Config,
+	finalCluster spec.Topology,
```
Comment (AstroProfundis) [inline pkg/cluster/operation/action.go:461]: How about passing a PD client object to the function, I think the `tlsCfg` could also be removed that way.

Comment (9547) [reply pkg/cluster/operation/action.go:461]: Since `Instance` is an abstraction interface used by both TiDB and DM, while PD only exists in the TiDB scenario. IMHO it is not very good to pass PD client as parameters, or we can abstract a `MetaClient` interface, whose responsibility is for these metadata operations by the client, but the kinds of metadata operation in TIDB and DM are so different, seems hard to abstract.

Comment (lucklove) [reply pkg/cluster/operation/action.go:461]: Then what about put the base topology into ctx since we may access it anywhere? Insert it at here: https://github.com/pingcap/tiup/blob/master/pkg/cluster/manager/scale_out.go#L151

Comment (9547) [reply pkg/cluster/operation/action.go:461]: sounds good to me.

**Comment by 9547** [comment]
@AstroProfundis @lucklove  PTAL

File: pkg/cluster/spec/tiflash.go [hunk 2]
```diff
@@ -640,25 +641,36 @@ type replicateConfig struct {
...
+	if topo == nil {
+		topo = i.topo
+	}
+
+	topo, ok := topo.(Topology)
+	if !ok {
+		return perrs.New("base topology in context is invalid")
 	}
 
+	endpoints := i.getEndpoints(topo.(Topology))
```
Comment (AstroProfundis) [inline pkg/cluster/spec/tiflash.go:673]:
```suggestion
	endpoints := i.getEndpoints(topo)
```

Comment (9547) [reply pkg/cluster/spec/tiflash.go]: Sorry, the variable `topo` was firstly introduced in line 663, that is the value of context, its type is `interface{}`,  the line 668 short variable declaration doesn't change its type.

I'll change the code style above to make it more maintainable.

File: pkg/cluster/spec/tiflash.go [hunk 3]
```diff
@@ -652,25 +653,37 @@ type replicateConfig struct {
...
+func (i *TiFlashInstance) PrepareStart(ctx context.Context, tlsCfg *tls.Config) error {
 	// set enable-placement-rules to true via PDClient
-	pdClient := api.NewPDClient(endPoints, 10*time.Second, tlsCfg)
 	enablePlacementRules, err := json.Marshal(replicateConfig{
 		EnablePlacementRules: "true",
 	})
+	// this should not failed, else exit
 	if err != nil {
-		return nil
+		return err
```
Comment (lucklove) [inline pkg/cluster/spec/tiflash.go:672]:
```suggestion
		return errors.Annotate(err, "failed to marshal replicate config")
```

File: pkg/cluster/operation/action.go [hunk 4]
```diff
@@ -470,7 +470,7 @@ func StartComponent(ctx context.Context, instances []spec.Instance, options Opti
 		// of checkpoint context every time put it into a new goroutine.
 		nctx := checkpoint.NewContext(ctx)
 		errg.Go(func() error {
-			if err := ins.PrepareStart(tlsCfg); err != nil {
+			if err := ins.PrepareStart(ctx, tlsCfg); err != nil {
```
Comment (lucklove) [inline pkg/cluster/operation/action.go:473]: Use `nctx` in case we add checkpoint in `PrepareStart` in the future.

File: pkg/cluster/spec/tiflash.go (hunk 3 above)
Comment (lucklove) [reply pkg/cluster/spec/tiflash.go:672]: We should give an annotate when received an error from third-party lib or standard lib.

File: pkg/cluster/operation/action.go (hunk 4 above)
Comment (9547) [reply pkg/cluster/operation/action.go:473]: +1
