### PR TITLE
cluster: fix malformed commands in local executor

### LINKED ISSUE #1268: tiup cluster with --ssh none failed on malformed command(nested single quote)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```bash
tiup cluster deploy foobar nightly ./topo.yaml --ssh none
```

2. What did you expect to see?

normally run tiup cluster with `--ssh none`

3. What did you see instead?

```
task.env_init.failed: Failed to initialize TiDB environment on remote host '127.0.0.1', cause: task.env_init.sub_command_failed: Failed to create '~/.ssh' directory for user 'tison', cause: executor.ssh.execute_failed: Failed to execute command locally {ssh_stderr: usage: mkdir [-pv] [-m mode] directory ...
, ssh_stdout: , ssh_command: export LANG=C; PATH=$PATH:/usr/bin:/usr/sbin sudo -H -u root bash -c 'cd; su - tison -c 'mkdir -p ~/.ssh && chmod 700 ~/.ssh''}, cause: exit status 64
 at github.com/pingcap/tiup/pkg/cluster/executor.(*Local).Execute()
	github.com/pingcap/tiup/pkg/cluster/executor/local.go:87
 at github.com/pingcap/tiup/pkg/cluster/executor.(*CheckPointExecutor).Execute()
	github.com/pingcap/tiup/pkg/cluster/executor/checkpoint.go:85
 at github.com/pingcap/tiup/pkg/cluster/task.(*EnvInit).execute()
	github.com/pingcap/tiup/pkg/cluster/task/env_init.go:81
 at github.com/pingcap/tiup/pkg/cluster/task.(*EnvInit).Execute()
	github.com/pingcap/tiup/pkg/cluster/task/env_init.go:47
 at github.com/pingcap/tiup/pkg/cluster/task.(*Serial).Execute()
	github.com/pingcap/tiup/pkg/cluster/task/task.go:85
 at github.com/pingcap/tiup/pkg/cluster/task.(*StepDisplay).Execute()
	github.com/pingcap/tiup/pkg/cluster/task/step.go:87
 at github.com/pingcap/tiup/pkg/cluster/task.(*Parallel).Execute.func1()
	github.com/pingcap/tiup/pkg/cluster/task/task.go:134
 at runtime.goexit()
```

obviously, `sudo -H -u root bash -c 'cd; su - tison -c 'mkdir -p ~/.ssh && chmod 700 ~/.ssh''` is malformed command.

4. What version of TiUP are you using (`tiup --version`)?

```
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Fix #1268 

### What is changed and how it works?
Adjust commands to use `'` for `sed` instead of `"` and properly escape `"` in commands.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cluster/executor/local.go [hunk 1]
```diff
@@ -41,11 +41,14 @@ var _ ctxt.Executor = &Local{}
 
 // Execute implements Executor interface.
 func (l *Local) Execute(ctx context.Context, cmd string, sudo bool, timeout ...time.Duration) ([]byte, []byte, error) {
+	// change wd to default home
+	cmd = fmt.Sprintf("cd; %s", cmd)
+
```
Comment (srstack) [inline pkg/cluster/executor/local.go:46]:
```suggestion
	// get current user name
	user, err := user.Current()
	if err != nil {
		return nil, nil, err
	}

```

File: pkg/cluster/executor/local.go [hunk 2]
```diff
@@ -41,11 +41,14 @@ var _ ctxt.Executor = &Local{}
...
 	// try to acquire root permission
 	if l.Sudo || sudo {
-		cmd = fmt.Sprintf("/usr/bin/sudo -H -u root bash -c 'cd; %s'", cmd)
+		cmd = fmt.Sprintf("/usr/bin/sudo -H -u root bash -c \"%s\"", strings.ReplaceAll(cmd, "\"", "\\\""))
 	} else {
```
Comment (srstack) [inline pkg/cluster/executor/local.go:50]:
```suggestion
	} else if l.Config.User != user.Name {
```

**Review by srstack — APPROVED** [review]
