### PR TITLE
Fix: destroy monitor if no more components in host

### LINKED ISSUE #842: When you scale-in PD, node_exporter of the PD node is still present
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

There is only pd service on 172.16.5.142, after executing tiup cluster scale-in lwt-cluster -N 172.16.5.142:2494, you can still see node_exporter and blackbox_exporter  exist on 172.16.5.142.

yaml:
image

tiup cluster scale-in lwt-cluster -N 172.16.5.142:2494
image

2. What did you expect to see?
When you deploy without mixing, scale-in needs to clean up node_exporter and blackbox_exporter.

3. What did you see instead?

image
image

4. What version of TiUP are you using (`tiup --version`)?
[tidb@node5162 ~]$ tiup cluster --version
Starting component `cluster`: /home/tidb/.tiup/components/cluster/v1.2.0/tiup-cluster --version
tiup version v1.2.0 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 1a4fbe7
[tidb@node5162 ~]$ tiup --version
v1.1.2 tiup
Go Version: go1.13
Git Branch: release-1.1
GitHash: 7cb85b9-dirty

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
fix #842 

### What is changed and how it works?

After scale-in component, check whether the host has any more components, if not, stop and destroy the monitor components.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test 

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Comment by 9547** [comment]
@AstroProfundis PTAL

File: components/dm/command/scale_in.go [hunk 1]
```diff
@@ -100,23 +102,46 @@ func ScaleInDMCluster(
 	}
 
 	// Cannot delete all DM DMMaster servers
-	if len(deletedDiff[dm.ComponentDMMaster]) == len(spec.Masters) {
+	if len(deletedDiff[dm.ComponentDMMaster]) == len(topo.Masters) {
 		return errors.New("cannot delete all dm-master servers")
 	}
 
+	maybeDestroyMonitor := func(instance spec.Instance) error {
```
Comment (lucklove) [inline components/dm/command/scale_in.go:109]: I think there is no need to destroy monitored instance in dm cluster since dm doesn't support monitored instance at all: https://github.com/pingcap/tiup/blob/master/components/dm/spec/topology_dm.go#L89

File: pkg/cluster/operation/scale_in.go [hunk 2]
```diff
@@ -122,29 +124,68 @@ func ScaleInCluster(
...
+		if err := DestroyComponent(getter, []spec.Instance{instance}, cluster, options); err != nil {
+			if !ignoreErr {
+				return errors.Annotatef(err, "failed to destroy %s", component.Name())
+			}
+			log.Warnf("failed to destroy %s: %v", component.Name(), err)
+		}
+
+		monitoredOptions := cluster.GetMonitoredOptions()
+		instCount[instance.GetHost()]--
+		if instCount[instance.GetHost()] == 0 && cluster.GetMonitoredOptions() != nil {
```
Comment (lucklove) [inline pkg/cluster/operation/scale_in.go:158]: cluster.GetMonitoredOptions() != nil is not needed because it's always true here: https://github.com/pingcap/tiup/blob/master/pkg/cluster/spec/spec.go#L192

File: pkg/cluster/operation/scale_in.go [hunk 3]
```diff
@@ -230,11 +255,8 @@ func ScaleInCluster(
...
 			if !asyncOfflineComps.Exist(instance.ComponentName()) {
-				if err := StopComponent(getter, []spec.Instance{instance}, options.OptTimeout); err != nil {
-					return errors.Annotatef(err, "failed to stop %s", component.Name())
-				}
-				if err := DestroyComponent(getter, []spec.Instance{instance}, cluster, options); err != nil {
-					return errors.Annotatef(err, "failed to destroy %s", component.Name())
+				if err := offlineInstance(component, instance); err != nil {
+					return err
 				}
 			} else {
```
Comment (lucklove) [inline pkg/cluster/operation/scale_in.go:261]: We should do the same thing for asyncOfflineComps too. Example: when you scale-in a tikv node, it will not be remove at once, instead, the PD server will transfer it's data to another tikv node, after that, the user can execute the prune command (https://github.com/pingcap/tiup/blob/master/components/cluster/command/prune.go#L45) to remove that TiKV (stop & destroy). The prune command will call `DestroyClusterTombstone` finally, so I think we should implement the same logic in DestroyClusterTombstone(https://github.com/pingcap/tiup/blob/master/pkg/cluster/operation/action.go#L178)

**Review by lucklove — COMMENTED** [review]
Thanks for your contributes, 9547, it really awesome!

File: components/dm/command/scale_in.go (hunk 1 above)
Comment (9547) [reply components/dm/command/scale_in.go:109]: Thanks for the advice, revert this commit

File: pkg/cluster/operation/scale_in.go (hunk 2 above)
Comment (9547) [reply pkg/cluster/operation/scale_in.go:158]: Sorry, this logical is forked from https://github.com/pingcap/tiup/blob/7aa4ea40705925f32e3033854e3bb786e87395e9/pkg/cluster/operation/destroy.go#L75-L79

In which case, the cluster may be tidb or dm, don't think too much, just copied it out.

File: pkg/cluster/operation/scale_in.go (hunk 3 above)
Comment (9547) [reply pkg/cluster/operation/scale_in.go:227]: implemented in daf3e3a

**Comment by 9547** [comment]
@lucklove PTAL

File: pkg/cluster/operation/destroy.go [hunk 4]
```diff
@@ -91,6 +90,46 @@ func Destroy(
 	return nil
 }
 
+// StopAndDestroyInstance stop and destroy the instance,
+// if this instance is the host's last one, and the host has monitor deployed,
+// we need to destroy the monitor, either
+func StopAndDestroyInstance(getter ExecutorGetter, component spec.Component, cluster spec.Topology, instance spec.Instance, options Options, destroyMonitor bool) error {
```
Comment (lucklove) [inline pkg/cluster/operation/destroy.go:96]: I think you can remove the `component` arg and use `instance.ComponentName()` or `instance.ID()` instead.

Comment (9547) [reply pkg/cluster/operation/destroy.go:96]: This arg is reserved, maybe has other usage later

Comment (lucklove) [reply pkg/cluster/operation/destroy.go:96]: Then what about add it back when we really need it?

Comment (9547) [reply pkg/cluster/operation/destroy.go:96]: LGTM

**Comment by 9547** [comment]
@lucklove PTAL again

File: pkg/cluster/operation/destroy.go [hunk 5]
```diff
@@ -91,6 +90,46 @@ func Destroy(
 	return nil
 }
 
+// StopAndDestroyInstance stop and destroy the instance,
+// if this instance is the host's last one, and the host has monitor deployed,
+// we need to destroy the monitor, either
+func StopAndDestroyInstance(getter ExecutorGetter, compName string, cluster spec.Topology, instance spec.Instance, options Options, destroyMonitor bool) error {
```
Comment (lucklove) [inline pkg/cluster/operation/destroy.go:96]: We can fetch the compName from `instance.ComponentName()`, so it can be removed at this time....

File: pkg/cluster/operation/destroy.go [hunk 6]
```diff
@@ -368,3 +407,191 @@ func DestroyComponent(getter ExecutorGetter, instances []spec.Instance, cls spec
...
+	filterID := func(instance []spec.Instance, id string) (res []spec.Instance) {
+		for _, ins := range instance {
+			if ins.ID() == id {
+				res = append(res, ins)
+			}
+		}
+		return
+	}
+
+	maybeDestroyMonitor := func(comp spec.Component, instances []spec.Instance, id string) error {
```
Comment (lucklove) [inline pkg/cluster/operation/destroy.go:455]: And if we remove the arg `compName` from `StopAndDestroyInstance`, the `comp` arg for `maybeDestroyMonitor` is not needed

File: pkg/cluster/operation/destroy.go [hunk 7]
```diff
@@ -368,3 +407,191 @@ func DestroyComponent(getter ExecutorGetter, instances []spec.Instance, cls spec
...
+		}
+
+		nodes = append(nodes, id)
+		if returNodesOnly {
+			continue
+		}
+
+		instances := (&spec.TiFlashComponent{Specification: cluster}).Instances()
+		id = s.Host + ":" + strconv.Itoa(s.GetMainPort())
+		if err := maybeDestroyMonitor(&spec.TiKVComponent{}, instances, id); err != nil {
```
Comment (lucklove) [inline pkg/cluster/operation/destroy.go:524]: It should not be `&spec.TiKVComponent{}` and it should be removed

File: pkg/cluster/operation/destroy.go [hunk 8]
```diff
@@ -368,3 +407,191 @@ func DestroyComponent(getter ExecutorGetter, instances []spec.Instance, cls spec
...
+			drainerServers = append(drainerServers, s)
+		}
+
+		nodes = append(nodes, id)
+		if returNodesOnly {
+			continue
+		}
+
+		instances := (&spec.DrainerComponent{Specification: cluster}).Instances()
+		if err := maybeDestroyMonitor(&spec.TiKVComponent{}, instances, id); err != nil {
```
Comment (lucklove) [inline pkg/cluster/operation/destroy.go:582]: ditto

**Review by lucklove — COMMENTED** [review]
Rest LGTM

File: components/dm/command/scale_in.go [hunk 9]
```diff
@@ -100,23 +99,17 @@ func ScaleInDMCluster(
...
 					continue
 				}
-				// just try stop and destroy
-				if err := operator.StopComponent(getter, []dm.Instance{instance}, options.OptTimeout); err != nil {
-					log.Warnf("failed to stop %s: %v", component.Name(), err)
-				}
-				if err := operator.DestroyComponent(getter, []dm.Instance{instance}, spec, options); err != nil {
-					log.Warnf("failed to destroy %s: %v", component.Name(), err)
-				}
+				_ = operator.StopAndDestroyInstance(getter, component.Name(), topo, instance, options, false)
```
Comment (lonng) [inline components/dm/command/scale_in.go:112]: We shouldn't ignore the error, please use `log.Warnf` if this error is not critical.

File: pkg/cluster/operation/scale_in.go [hunk 10]
```diff
@@ -122,66 +124,55 @@ func ScaleInCluster(
...
 
-				// just try stop and destroy
-				if err := StopComponent(getter, []spec.Instance{instance}, options.OptTimeout); err != nil {
-					log.Warnf("failed to stop %s: %v", component.Name(), err)
-				}
-				if err := DestroyComponent(getter, []spec.Instance{instance}, cluster, options); err != nil {
-					log.Warnf("failed to destroy %s: %v", component.Name(), err)
-				}
+				instCount[instance.GetHost()]--
+				_ = StopAndDestroyInstance(getter, compName, cluster, instance, options, instCount[instance.GetHost()] == 0)
```
Comment (AstroProfundis) [inline pkg/cluster/operation/scale_in.go:154]: This error should be handled too

File: pkg/cluster/operation/destroy.go (hunk 5 above)
Comment (9547) [reply pkg/cluster/operation/destroy.go:96]: Thanks for the advice.

File: pkg/cluster/operation/destroy.go [hunk 11]
```diff
@@ -368,3 +407,191 @@ func DestroyComponent(getter ExecutorGetter, instances []spec.Instance, cls spec
...
+			pumpServers = append(pumpServers, s)
+		}
+
+		nodes = append(nodes, id)
+		if returNodesOnly {
+			continue
+		}
+
+		instances := (&spec.PumpComponent{Specification: cluster}).Instances()
+		if err := maybeDestroyMonitor(&spec.TiKVComponent{}, instances, id); err != nil {
```
[the remark this answers is not in the document]
Comment (9547) [reply pkg/cluster/operation/destroy.go:553]: This arg will be removed from `maybeDestroyMonitor`, and thanks to @lucklove 's advice

**Comment by 9547** [comment]
@lucklove Please help me about the test failure, curious about the test failure reason (exit 255), and it runs successful on my local dev env

**Comment by lucklove** [comment]
> @lucklove Please help me about the test failure, curious about the test failure reason (exit 255), and it runs successful on my local dev env

It's because of this:
> fail to wait instance number reach 20, count 21, retry num: 120

**Comment by lucklove** [comment]
It's because there is a TiKV node that is still in offline process:
```
172.19.0.102:20160  tikv            172.19.0.102  20160/20180                      linux/x86_64  Pending Offline
```

File: tests/tiup-cluster/script/scale_core.sh [hunk 12]
```diff
@@ -62,13 +64,38 @@ function scale_core() {
...
-
     # after scalue-out, ensure this instance come back
     tiup-cluster $client exec $name -N $ipprefix.101 --command "grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh"
 
+    echo "start scale in node-2 with [tidb, tikv]"
+    tiup-cluster $client --yes scale-in $name -N $ipprefix.102:4000
+    wait_instance_num_reach $name $total_sub_one $native_ssh
+    tiup-cluster $client --yes scale-in $name -N $ipprefix.102:20160
+    echo "after sclae in(without prune) tikv, the monitors should not be destroyed"
+    wait_instance_num_reach $name $total_sub_one $native_ssh
```
Comment (lucklove) [inline tests/tiup-cluster/script/scale_core.sh:80]: > after sclae in(without prune) tikv, the monitors should not be destroyed

`waiit_instance_num_reach` will call prune automaticlly, this is not what you expected

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh:80]: but why it was passed in my local dev

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh:80]: I'll dig into later tonight, and thanks for your help 😀

Comment (lucklove) [reply tests/tiup-cluster/script/scale_core.sh:80]: It passed in your local dev, I think it may related to the opportunity:
- Only when the tikv's state is tombstone, the prune command cleanup it
- After scale in a tikv node, it will take some time to transfer to tombstone state (seconds to minutes)
So I guess your local host, when the `wait_instance_num_reach` execute, the tikv node is still in `pending offline` state, so it passed, but in CI, the tikv node is `tombstone`, so it was cleanup.

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh]: 1. Seems in Github CI, it's hard to predicate when TiKV will finish the transferring process and go to tombstone state, after that `prune` can evict the TiKV. 
2.  have reserved only one TIDB node on the 102 node for testing the issue #842

**Review by lucklove — APPROVED** [review]
LGTM
