### PR TITLE
cluster: add ngm metrics to promtheus config

### LINKED ISSUE #1799: prometheus doesn't monitoring the ng-monitoring component
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Currently, Prometheus doesn't have metrics data about ng-monitoring, since Prometheus config doesn't contain ng-monitoring address.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?
```shell
▶ tiup --version
1.9.2 tiup
Go Version: go1.17.7
Git Ref: v1.9.2
GitHash: d90f3eb81e145621c3880c320b88bf10c6f03a70

```

### LINKED ISSUE #1809: promtheus not connect to node-exporter which node that only has promtheus
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

### PR DESCRIPTION
**Pull request by nexustar**
### What problem does this PR solve? 

- close #1799 
- fix #1809

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by crazycs520 — APPROVED** [review]

File: pkg/cluster/spec/monitoring.go [hunk 1]
```diff
@@ -254,6 +254,13 @@ func (i *MonitorInstance) InitConfig(
 			cfig.AddCDC(cdc.Host, uint64(cdc.Port))
 		}
 	}
+	if servers, found := topoHasField("Monitors"); found {
+		for i := 0; i < servers.Len(); i++ {
+			monitoring := servers.Index(i).Interface().(*PrometheusSpec)
+			uniqueHosts.Insert(monitoring.Host)
+			cfig.AddNGMonitoring(monitoring.Host, uint64(monitoring.NgPort))
```
Comment (AstroProfundis) [inline pkg/cluster/spec/monitoring.go:261]: What will happen if there is no ngm instance available in the cluster?

File: pkg/cluster/template/config/prometheus.go [hunk 2]
```diff
@@ -172,13 +158,13 @@ func (c *PrometheusConfig) AddBlackbox(ip string, port uint64) *PrometheusConfig
...
-func (c *PrometheusConfig) AddKafkaExporter(ip string, port uint64) *PrometheusConfig {
-	c.KafkaExporterAddr = fmt.Sprintf("%s:%d", ip, port)
+// AddNGMonitoring add an ng-monitoring server exporter address
+func (c *PrometheusConfig) AddNGMonitoring(ip string, port uint64) *PrometheusConfig {
+	c.NGMonitoringAddrs = append(c.NGMonitoringAddrs, fmt.Sprintf("%s:%d", ip, port))
 	return c
 }
 
-// AddGrafana add an kafka exporter address
+// AddGrafana add an Grafana exporter address
```
Comment (AstroProfundis) [inline pkg/cluster/template/config/prometheus.go:167]:
```suggestion
// AddGrafana add an Grafana address
```

**Review by AstroProfundis — APPROVED** [review]
