### PR TITLE
fix edit-cluster help information

### LINKED ISSUE #1898: Edit config help information has an incorrect newline mark
## Bug Report

See: https://github.com/pingcap/tiup/blob/master/components/cluster/command/edit_config.go#L25

Which will cause `tiup cluster -h` display incorrect newline after `edit-config`

```
➜  ~ tiup cluster -h
Deploy a TiDB cluster for production

Usage:
  tiup-cluster [command]

Available Commands:
  check       Perform preflight checks for the cluster.
  deploy      Deploy a cluster for production
  start       Start a TiDB cluster
  stop        Stop a TiDB cluster
  restart     Restart a TiDB cluster
  scale-in    Scale in a TiDB cluster
  scale-out   Scale out a TiDB cluster
  destroy     Destroy a specified cluster
  clean       (EXPERIMENTAL) Cleanup a specified cluster
  upgrade     Upgrade a specified TiDB cluster
  display     Display information of a TiDB cluster
  prune       Destroy and remove instances that is in tombstone state
  list        List all clusters
  audit       Show audit log of cluster operation
  import      Import an exist TiDB cluster from TiDB-Ansible
  edit-config Edit TiDB cluster config.
Will use editor from environment variable `EDITOR`, default use vi
  show-config Show TiDB cluster config
  reload      Reload a TiDB cluster's config and restart if needed
  patch       Replace the remote package with a specified package and restart the service
  rename      Rename the cluster
  enable      Enable a TiDB cluster automatically at boot
  disable     Disable automatic enabling of TiDB clusters at boot
  replay      Replay previous operation and skip successed steps
  template    Print topology template
  tls         Enable/Disable TLS between TiDB components
  help        Help about any command
  completion  Generate the autocompletion script for the specified shell

Flags:
  -c, --concurrency int     max number of parallel tasks allowed (default 5)
      --format string       (EXPERIMENTAL) The format of output, available values are [default, json] (default "default")
  -h, --help                help for tiup-cluster
      --ssh string          (EXPERIMENTAL) The executor type: 'builtin', 'system', 'none'.
      --ssh-timeout uint    Timeout in seconds to connect host via SSH, ignored for operations that don't need an SSH connection. (default 5)
  -v, --version             version for tiup-cluster
      --wait-timeout uint   Timeout in seconds to wait for an operation to complete, ignored for operations that don't fit. (default 120)
  -y, --yes                 Skip all confirmations and assumes 'yes'
```

### PR DESCRIPTION
**Pull request by nexustar**
### What problem does this PR solve? 

- fix #1898 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by srstack — APPROVED** [review]

File: components/dm/command/edit_config.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ func newEditConfigCmd() *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "edit-config <cluster-name>",
 		Short: "Edit DM cluster config",
+		Long:  "Edit DM cluster config.\nWill use editor from environment variable `EDITOR`, default use vi",
```
Comment (lonng) [inline components/dm/command/edit_config.go:26]: Can we remove the `\n`?
