### PR TITLE
*: fix broken depends and update

### LINKED ISSUE #1360: compile error repository 'https://github.com/xo/xoutil/' not found
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
make tiup
```

2. What did you expect to see?

Compile successfully.

3. What did you see instead?

```
GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -ldflags '-w -s -X "github.com/pingcap/tiup/pkg/version.GitHash=2afe65d" -X "github.com/pingcap/tiup/pkg/version.GitRef=patch-1"' -o bin/tiup
go: github.com/xo/usql@v0.7.8 requires
	github.com/xo/xoutil@v0.0.0-20171112033149-46189f4026a5: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/yangkeao/go/pkg/mod/cache/vcs/076de485f6bfc7a8e444ab6a676f8b3bebc02186cfe92720dd78cec82eafcc82: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/xo/xoutil/' not found
make: *** [Makefile:54: tiup] Error 1
```
This repo doesn't exist, and GitHub returns 404 for it.

4. What version of TiUP are you using (`tiup --version`)?

Don't know, as it failed to compile...

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Fix #1360 and update some depends

### What is changed and how it works?

 - Split `client` and `bench` to dedicated Go packages to avoid dependency conflicts
 - Upgrade `usql` to remove dependency of `xoutil`
 - Upgrade `etcd` to latest to avoid conflict of `usql`
 - Upgrade other depends with `go mod tidy`

### Check List 

Tests 

 - Unit test

Release notes:

```release-note
*: fix broken depends and update
```

### CODE REVIEW

**Review by YangKeao — APPROVED** [review]
LGTM

File: components/client/main.go [hunk 1]
```diff
@@ -93,8 +103,8 @@ func connect(target string) error {
 	if err != nil {
 		return fmt.Errorf("can't open history file: %s", err.Error())
 	}
-	h := handler.New(l, u, os.Getenv(localdata.EnvNameInstanceDataDir), true)
-	if err = h.Open(ep.dsn); err != nil {
+	h := handler.New(l, u, os.Getenv(EnvNameInstanceDataDir), true)
+	if err = h.Open(context.Background(), ep.dsn); err != nil {
```
Comment (lucklove) [inline components/client/main.go:107]:
```suggestion
	if err = h.Open(context.TODO(), ep.dsn); err != nil {
```
