### PR TITLE
Refine the error message of monitor port conflict

### LINKED ISSUE #965: The error message of monitor port conflict is misleading
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I try to deploy a cluster that has a monitor port conflict with a previous cluster. TiUP tells me that there exists a port conflict between pd and tiflash:
```
>  tiup cluster deploy j2 v4.0.8 topo.yaml 
Error: Deploy port conflicts to an existing cluster (spec.deploy.port_conflict)

The port you specified in the topology file is:
  Port:      9110
  Component: pd 172.16.5.81

It conflicts to a port in the existing cluster:
  Existing Cluster Name: xxx
  Existing Port:         9110
  Existing Component:    tiflash 172.16.5.81

Please change to use another port or another host.
```
But the port 9110 is the port of monitored.node_exporter_port

2. What did you expect to see?

TiUP tells me that there exists a port conflict of monitor port

3. What did you see instead?

TiUP tells me that there exists a port conflict between pd and tiflash

4. What version of TiUP are you using (`tiup --version`)?

v1.2.5 tiup
Go Version: go1.13
Git Branch: release-1.2
GitHash: 5b9cf5d

### PR DESCRIPTION
**Pull request by JaySon-Huang**
Signed-off-by: JaySon-Huang <tshent@qq.com>

### What problem does this PR solve? 
Fix #965. Refine the error message of monitor port conflict.

### What is changed and how it works?
Use `spec.RoleMonitor` as the component name instead of the instance name.

### Check List 

Tests 

 - Unit test

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
Refine the error message of monitor port conflict
```

### CODE REVIEW

File: pkg/cluster/spec/validate.go [hunk 1]
```diff
@@ -222,23 +223,26 @@ func CheckClusterPortConflict(clusterList map[string]Metadata, clusterName strin
 			blackboxExporterPort := mOpt.BlackboxExporterPort
 			for _, port := range inst.UsedPorts() {
 				existingEntries = append(existingEntries, Entry{
-					clusterName: name,
-					instance:    inst,
-					port:        port,
+					clusterName:   name,
+					componentName: inst.ComponentName(),
+					host:          inst.GetHost(),
```
Comment (AstroProfundis) [inline pkg/cluster/spec/validate.go:228]: Um, I didn't quite get the point of adding a new field, we could use `inst.GetHost()` to get the value anytime.

File: pkg/cluster/spec/validate_test.go [hunk 2]
```diff
@@ -428,12 +428,12 @@ tidb_servers:
 	c.Assert(ok, IsTrue)
 	c.Assert(suggestion, Equals, `The port you specified in the topology file is:
   Port:      9100
-  Component: tidb 172.16.5.138
+  Component: monitor 172.16.5.138
```
Comment (AstroProfundis) [inline pkg/cluster/spec/validate_test.go:431]: Did you tested if the conflict is between a tidb node and a pd node but not with their monitoring agent's ports?

File: pkg/cluster/spec/validate.go (hunk 1 above)
Comment (JaySon-Huang) [reply pkg/cluster/spec/validate.go:228]: I try to make the message contains in `Entry` is clear and eliminate the ambiguous. If there exist fields `port`, `componentName` along with `inst`, should I get the port from `inst.GetPort()` or `inst.ComponentName()`?
However, keeping `inst` instead of adding `host` is more flexible.

I can keep `inst` instead of adding `host` if you insist.

File: pkg/cluster/spec/validate_test.go (hunk 2 above)
Comment (JaySon-Huang) [reply pkg/cluster/spec/validate_test.go:431]: The 9100 is the default port of the monitoring agent.
And I debug the code step by step to know that the conflict is monitoring agent after seeing the misleading error message https://github.com/pingcap/tiup/issues/965#issuecomment-738515276

For the test case that conflicts between tidb node and pd node but not their monitoring agent's, there is a test case between pump_server and pd in the following lines.

File: pkg/cluster/spec/validate.go (hunk 1 above)
Comment (AstroProfundis) [reply pkg/cluster/spec/validate.go:228]: Yes I would still suggest using `inst` as it carries more information.

**Review by AstroProfundis — APPROVED** [review]
