### PR TITLE
cluster: fix Grafana error  datasource not found 

### LINKED ISSUE #1762: Grafana：datasource not found
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

tiup cluster reload/restart cluster

2. What did you expect to see?

image

3. What did you see instead?

origin_img_v2_a75e7274-ad21-4bc9-a53a-d55cad9a84fg

4. What version of TiUP are you using (`tiup --version`)?
1.9.0

### PR DESCRIPTION
**Pull request by srstack**
### What problem does this PR solve? 

close #1762 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

**Review by nexustar — APPROVED** [review]

File: pkg/cluster/manager/destroy.go [hunk 1]
```diff
@@ -166,7 +166,8 @@ func (m *Manager) DestroyTombstone(
 		UpdateMeta(name, clusterMeta, nodes).
 		UpdateTopology(name, m.specManager.Path(name), clusterMeta, nodes).
 		ParallelStep("+ Refresh instance configs", gOpt.Force, regenConfigTasks...).
-		ParallelStep("+ Reloda prometheus", gOpt.Force, buildReloadPromTasks(metadata.GetTopology(), m.logger, gOpt)...).
+		ParallelStep("+ Reloda prometheus and grafanas", gOpt.Force,
```
Comment (AstroProfundis) [inline pkg/cluster/manager/destroy.go:169]:
```suggestion
		ParallelStep("+ Reload prometheus and grafana", gOpt.Force,
```

File: pkg/cluster/manager/scale_in.go [hunk 2]
```diff
@@ -116,7 +116,8 @@ func (m *Manager) ScaleIn(
 
 	t := b.
 		ParallelStep("+ Refresh instance configs", force, regenConfigTasks...).
-		ParallelStep("+ Reloda prometheus", gOpt.Force, buildReloadPromTasks(metadata.GetTopology(), m.logger, gOpt, nodes...)...).
+		ParallelStep("+ Reloda prometheus and grafanas", gOpt.Force,
```
Comment (AstroProfundis) [inline pkg/cluster/manager/scale_in.go:119]:
```suggestion
		ParallelStep("+ Reload prometheus and grafana", gOpt.Force,
```
