### PR TITLE
Playground: support setting custom timeout for waiting instances up

### LINKED ISSUE #962: Playground incorrectly detected that tidb failed to start
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
tiup playground --host 0.0.0.0 --tiflash 1
```

2. What did you expect to see?

outputs
```
To connect TiDB: mysql --host %s --port %s -u root
```
and start tiflash

3. What did you see instead?

tidb start successfully but outputs

```
Playground Bootstrapping...
Start pd instance
Start tikv instance
Start tidb instance
Waiting for tidb localhost:4000 ready  ... Error
To view the dashboard: http://localhost:2379/dashboard
To view the Prometheus: http://0.0.0.0:9090
To view the Grafana: http://0.0.0.0:3000
```

4. What version of TiUP are you using (`tiup --version`)?

```
v1.2.0 tiup
Go Version: go1.13
Git Branch: bump
GitHash: 7e35be8
```

--- 

I use tiup in Ubuntu 18 for WSL. And this happens occasionally.

### PR DESCRIPTION
**Pull request by unbyte**
### What problem does this PR solve? 

#962 

Currently tiup playground will wait for tidb up in 60 seconds, and if it fails, tiflash instance will be ignored. However, sometimes tidb instances start normally but only the startup time exceeds the timeout time. So maybe support setting custom timeout for waiting instances up can help.

### What is changed and how it works?

1. add two flag
```
--db.timeout int           TiDB max wait time in seconds for staring, 0 means no limit (default 60)
--tiflash.timeout int      TiFlash max wait time in seconds for staring, 0 means no limit (default 120)
```

2. remove waiting for tikv

3. check tidb and tiflash status in parallel

image

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

--- 

close #962

### CODE REVIEW

**Comment by unbyte** [comment]
image

Noticed that even if a process such as tiflash exited with error, the function to check status is still polling (this problem exists in both the master branch and this PR). Maybe need to find a way to notify check functions when the process exits with error?

File: components/playground/playground.go [hunk 1]
```diff
@@ -785,68 +786,82 @@ func (p *Playground) bootCluster(ctx context.Context, env *environment.Environme
...
-		startTiFlash := func() error {
+		var started []*instance.TiFlashInstance
+		for _, flash := range p.tiflashs {
+			if err := p.startInstance(ctx, flash); err != nil {
+				fmt.Println(color.RedString("TiFlash %s failed to start: %s", flash.Addr(), err))
+			} else {
+				started = append(started, flash)
+			}
+		}
+		p.tiflashs = started
```
Comment (unbyte) [inline components/playground/playground.go:827]: ignore tiflash instances that fail to start like how master branch works. 
however, I think it's better to exit and throw error when fail to start tiflash just like other components.

Comment (lucklove) [reply components/playground/playground.go:827]: I think it's because TiFlash failed to start is not a critical issue, the cluster can still bootstrap. So it's better to ignore it and just print out a log to let the user know what happened.

Comment (unbyte) [reply components/playground/playground.go:827]: yeah it's reasonable. But IMO it is based on the fact that the number of tiflash instances defaults to 1 rather than 0 while some user actually don't intend to use tiflash. 
BTW, some days ago, I've found that both en and zh documentations say the number of tiflash instances defaults to 0. I wonder if it's neccessary to set the default number to 1.

Comment (lucklove) [reply components/playground/playground.go:827]: I think we should update the document. In early releases, it's 0. But we changed it to 1 in recent releases.

File: components/playground/main.go [hunk 2]
```diff
@@ -246,47 +250,43 @@ func tryConnect(dsn string) error {
...
 			return true
 		}
+		time.Sleep(time.Second)
 	}
-	return false
 }
 
-func checkStoreStatus(pdClient *api.PDClient, typ, storeAddr string) error {
-	prefix := color.YellowString("Waiting for %s %s ready ", typ, storeAddr)
-	bar := progress.NewSingleBar(prefix)
```
[the remark this answers is not in the document]
Comment (unbyte) [reply components/playground/main.go:267]: moved to bootCluster()

File: components/playground/playground.go [hunk 3]
```diff
@@ -785,68 +786,82 @@ func (p *Playground) bootCluster(ctx context.Context, env *environment.Environme
...
+		var wg sync.WaitGroup
+		bars := progress.NewMultiBar(color.YellowString("Waiting for tidb instances ready\n"))
+		for _, db := range p.tidbs {
+			wg.Add(1)
+			prefix := color.YellowString(db.Addr())
+			bar := bars.AddBar(prefix)
+			go func(dbInst *instance.TiDBInstance) {
+				defer wg.Done()
+				if s := checkDB(dbInst.Addr(), options.tidb.UpTimeout); s {
+					succ = append(succ, dbInst.Addr())
```
Comment (unbyte) [inline components/playground/playground.go:799]: may lose some successfully started instances, because slice is not thread safe. it's better to use channel so.

Comment (lucklove) [reply components/playground/playground.go:799]: Oh, yes. It's better to fix that...

**Comment by unbyte** [comment]
solved
