### PR TITLE
install.sh: check depends before downloading package

### LINKED ISSUE #1287: tiup does not check if curl/tar is available
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

From https://github.com/pingcap/docs/pull/5228

On manual inspection it does indeed use tar:
https://github.com/pingcap/tiup/blob/52e24c2ee45e6a2acc3bd59990a4f1ebbedcd633/install.sh#L38

2. What did you expect to see?

It would be nice if the script checked for dependencies (curl, tar) correctly before downloading, and then if it bails print the docs URL for help. i.e. https://docs.pingcap.com/tidb/stable/quick-start-with-tidb

3. What did you see instead?

The error message is only presented after the download.

4. What version of TiUP are you using (`tiup --version`)?

Confirmed by inspecting code against master.

### PR DESCRIPTION
**Pull request by AstroProfundis**
### What problem does this PR solve? 
Fix #1287 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Related changes

 - Need to cherry-pick to the release branch

Release notes:

```release-note
install.sh: check depends before downloading package
```

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -40,6 +40,23 @@ install_binary() {
     return 0
 }
 
+check_depends() {
+    pass=0
+    command -v curl >/dev/null || {
+        echo "Dependency check failed: please install 'curl' before installing."
+	pass=1
```
Comment (lucklove) [inline install.sh:47]:
```suggestion
	  pass=1
```

File: install.sh [hunk 2]
```diff
@@ -40,6 +40,23 @@ install_binary() {
     return 0
 }
```
Comment (lucklove) [inline install.sh:42]: Add this logic to local_insta.sh too.
