### PR TITLE
grafana: fix lightning's name not changed when cluster renamed

### LINKED ISSUE #1166: exec `tiup rename` ; Grafana dashboard lightning new and old documents
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiUP are you using (`tiup --version`)?

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
fix #1166 

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: embed/templates/scripts/run_grafana.sh.tpl [hunk 1]
```diff
@@ -6,6 +6,15 @@ set -e
 DEPLOY_DIR={{.DeployDir}}
 cd "${DEPLOY_DIR}" || exit 1
 
+# try to compatible with tidb-lightning's dashboard,
+# the tidb-lightning dashboard's uid is not set,
+# after the cluster renamed, the old dashboard will not be replaced with the newly one.
```
Comment (lucklove) [inline embed/templates/scripts/run_grafana.sh.tpl:11]: I checked old `dashboards/lightning.json` but there is no `uid` in this file. Is there something wrong?

File: embed/templates/scripts/run_grafana.sh.tpl [hunk 2]
```diff
@@ -6,6 +6,15 @@ set -e
 DEPLOY_DIR={{.DeployDir}}
 cd "${DEPLOY_DIR}" || exit 1
 
+# try to compatible with tidb-lightning's dashboard,
```
Comment (lucklove) [inline embed/templates/scripts/run_grafana.sh.tpl:9]: We need set this in https://github.com/pingcap/tidb-lightning/blob/master/metrics/grafana/lightning.json instead of set it with script in tiup-cluster. Because there are other tools depends on it, too.

Comment (9547) [reply embed/templates/scripts/run_grafana.sh.tpl:9]: Good idea, the _lightning.json_ needs to be modified,  and for the existing offline tarballs, we need to compatible and fix it.

File: embed/templates/scripts/run_grafana.sh.tpl [hunk 3]
```diff
@@ -6,6 +6,15 @@ set -e
...
+# the tidb-lightning dashboard's uid is not set,
+# after the cluster renamed, the old dashboard will not be replaced with the newly one.
+# and Grafana use the unique uid as indepent dashaboard.
+# this script was stolen from https://stackoverflow.com/a/13844351
+if [[ -f dashboards/lightning.json ]]; then
+    grep -qxF uid dashboards/lightning.json || sed -i '$s/}/,\n"uid":"t5PjsKUGz"}/' dashboards/lightning.json
```
Comment (lucklove) [inline embed/templates/scripts/run_grafana.sh.tpl:15]: So could you remove these lines and open a PR on https://github.com/pingcap/tidb-lightning/blob/master/metrics/grafana/lightning.json?

Comment (9547) [reply embed/templates/scripts/run_grafana.sh.tpl:15]: So for the Grafana package that has been released, are we not going to fix it, to keep the code simple?

Comment (lucklove) [reply embed/templates/scripts/run_grafana.sh.tpl:15]: Sorry for my mistake: https://github.com/PingCAP-QE/ci/blob/jenkins-pipelines/jenkins/pipelines/cd/tiup/grafana-tiup-mirror-update-test.groovy#L95

We should change BR instead...

Comment (lucklove) [reply embed/templates/scripts/run_grafana.sh.tpl:15]: > So for the Grafana package that has been released, are we not going to fix it, to keep the code simple?

No, we shouldn't change codesthat not belong to TiUP. (I think the xxx.json in other repos can be treated as code). The user can upgrade cluster if he really want to fix this.

**Comment by 9547** [comment]
@lucklove PTAL
