### PR TITLE
Fix/pd scale in topo not updated

### LINKED ISSUE #786: Scale-in PD node does not update TiDB startup script
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Deploy a cluster, then scale-in a PD node.

2. What did you expect to see?

The PD address in TiDB startup script is updated to latest topology.

3. What did you see instead?

TiDB startup script is unchanged.

4. What version of TiUP are you using (`tiup --version`)?

v1.1.1

### PR DESCRIPTION
**Pull request by 9547**
### What problem does this PR solve? 
fix #786 

### What is changed and how it works?

Delete pd instances in `topo.PDServers` if pd instances were removed.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

Release notes:

```release-note
Fix Scale-in PD Servers does not update TiDB startup script 
```

### CODE REVIEW

**Comment by 9547** [comment]
The test_scale_core_tls test case failed, and can be reproduced in local env, eg:

```bash
bash /tiup-cluster/tests/tiup-cluster/run.sh test_scale_core_tls
```

failed of scale in pd failed:

```bash
start scale in pd
+ [ Serial ] - SSHKeySet: privateKey=/root/.tiup/storage/cluster/clusters/test_scale_core_25107/ssh/id_rsa, publicKey=/root/.tiup/storage/cluster/clusters/test_scale_core_25107/ssh/id_rsa.pub
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.101
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.104
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.105
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.103
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.102
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.104
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.101
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.105
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.101
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.102
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.103
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.103
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.104
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.105
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.104
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.101
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.101
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.105
+ [Parallel] - UserSSH: user=tidb, host=172.19.0.103
+ [ Serial ] - ClusterOperate: operation=ScaleInOperation, options={Roles:[] Nodes:[172.19.0.103:2379] Force:false SSHTimeout:5 OptTimeout:120 APITimeout:300 IgnoreConfigCheck:false NativeSSH:false SSHType: CleanupData:false CleanupLog:false RetainDataRoles:[] RetainDataNodes:[]}
Error: failed to scale in: no endpoint available, the last err is: error requesting https://172.19.0.105:2379/pd/api/v1/members/name/pd-172.19.0.103-2379, response: "etcdserver: unhealthy cluster"
, code 500
```

dig into the _pd.log_:


```bash
[2020/09/28 22:31:22.322 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45176] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.322 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45174] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.424 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45194] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.425 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45196] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.522 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45212] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.522 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45214] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.622 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45232] [server-name=] [error="remote error: tls: bad certificate"]
[2020/09/28 22:31:22.622 +00:00] [WARN] [config_logging.go:279] ["rejected connection"] [remote-addr=172.19.0.104:45234] [server-name=] [error="remote error: tls: bad certificate"]
```

Maybe the TLS's certificate not updated after pd scale-in or some other error. I'll deep dive into it later.

**Comment by 9547** [comment]
maybe merged after #836

File: tests/tiup-cluster/script/scale_core.sh [hunk 1]
```diff
@@ -58,10 +58,17 @@ function scale_core() {
     echo "start scale in pd"
     tiup-cluster $client --yes scale-in $name -N $ipprefix.103:2379
     wait_instance_num_reach $name $total_sub_one $native_ssh
+
+    # validate https://github.com/pingcap/tiup/issues/786
+    # ensure that this instance is removed from the startup scripts of other components that need to rely on PD
+    tiup-cluster $client exec $name -N $ipprefix.101 --command "grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh && exit 1 || exit 0"
```
Comment (lucklove) [inline tests/tiup-cluster/script/scale_core.sh:64]: This may not work as you expected:

```sh
exit 1 && exit 1 || exit 0 # 1
exit 0 && exit 1 || exit 0 # 0
```
So 
```sh
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh && exit 1 || exit 0
```
is equivalent with
```
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh
```
Suggest using:
```
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh && exit 1
```

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh:64]: This is what I'm not expected, and thanks for your kindness advice. 😄

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh]: Sorry, I'm kind of forgetting where I left off, but it means we need the opposite result(ensure the pd backend was removed from config's file), so we need to rewrite the return code 

```bash
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh && exit 1 || exit 0"
```

and the below is enough:

```bash
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh || exit 0"
```

If found, then the return code is the one on left; else the right one(`0`), and that's what we want.

Comment (lucklove) [reply tests/tiup-cluster/script/scale_core.sh]:
```
grep -q $ipprefix.103:2379 /home/tidb/deploy/tidb-4000/scripts/run_tidb.sh || exit 0
```
Will always exit with 0.

If you need the opposite result, I think a single `!` is enough, something like
https://github.com/pingcap/tiup/blob/8aacd48c388f455e80a21bcecca282bdf3e2cc44/tests/tiup-cluster/script/cmd_subtest.sh#L94
(replace the `ls` command with `grep` command)

Comment (9547) [reply tests/tiup-cluster/script/scale_core.sh]: Thanks for the advice.

**Review by lucklove — APPROVED** [review]
LGTM
