### PR TITLE
manager: check for global configs and prompt user for confirmation on…

### LINKED ISSUE #1293: TiUP should raise error while scale-out with global configurations
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Scale-out with global configurations. We need to raise error for this if we do not support scale-out with global configurations.

2. What did you expect to see?
Raise error

3. What did you see instead?
Scale-out with global configurations successfully. But the configurations are not effective.

4. What version of TiUP are you using (`tiup --version`)?
```
$ tiup --version
1.4.0 tiup
Go Version: go1.16.2
Git Ref: v1.4.0
GitHash: eb335e6ad9d0dc19d1c43db422cd409d62bc3cea
```

### PR DESCRIPTION
**Pull request by AstroProfundis**
… scale-out

### What problem does this PR solve? 
Close #1293 

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Side effects

 - Increased code complexity

Release notes:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cluster/manager/scale_out.go [hunk 1]
```diff
@@ -168,3 +176,35 @@ func validateNewTopo(topo spec.Topology) (err error) {
...
+	if err := yaml.Unmarshal(yamlFile, &newPart); err != nil {
+		return err
+	}
+
+	for k := range newPart {
+		switch k {
+		case "global",
+			"monitored",
+			"server_configs":
+			log.Warnf(
```
Comment (lucklove) [inline pkg/cluster/manager/scale_out.go:198]: Use yellow color
